version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    command: npm run dev
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true
